import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { GraphQLClient, gql } from 'graphql-request'
import { GET_ALL_BLOGS } from '../graphQL/queries'
import graphQLClient from '../graphQL/graphQLClient'

// export const getStaticProps: GetStaticProps = async (context) => {

//   const endpoint = process.env.PREVIEW_EDGE_CH_ENDPOINT as string;

//   const graphQLClient = new GraphQLClient(endpoint)
//   graphQLClient.setHeader('X-GQL-Token', process.env.PREVIEW_EDGE_CH_API_KEY as string)

//   const query = gql`
//   {
//     allM_Content_Blog {
//       results{
//         blog_Title
//         blog_Body
//       }
//     }
//   }
// `
//   const data = await graphQLClient.request(query);

//   return {
//     props: { blogContent: data.allM_Content_Blog },
//   };
// }

export const getStaticProps: GetStaticProps = async (context) => {
  const data = await graphQLClient.request(GET_ALL_BLOGS);

  return {
    props: {blogContent: data.allM_Content_Blog}
  };
}

const Home: NextPage = (props: any) => {

  console.log(JSON.stringify(props, undefined, 2))

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Experience Edge for Content Hub
        </h1>

        <div className={styles.grid}>

          {props?.blogContent.results.map((blog: any) => (
            <a key={blog.blog_Title} className={styles.card}>
              <h2>{blog.blog_Title}</h2>
              <p>{blog.blog_Body}</p>
            </a>
          ))}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
